### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#43]
blog
Select a "web" group
"https://www.ivaro.sk/tagged/web"
Choose "read more"
An error occurred:

![pulse-blog - 12_4](https://user-images.githubusercontent.com/29908185/38657722-0f8fb30e-3e22-11e8-901c-bd2b84ab2a81.png)

Clarification of that error.
In a blog, select the "read more".
...........
PHP version 7.2

**Comment by ghost** [comment]
Had a look at https://www.ivaro.sk/tagged/web The blog item url looks ok. https://www.ivaro.sk/blog-6-A-Very-Nice-Blog-Post opens  

The bug report had an extra blog- in the blog url.

 That's not showing anymore on the site. So it looks like something has been fixed?

**Comment by IvaRoSoft** [comment]
The error still persists!
https://ivaro.sk/blog
Click on Read more => "Čítajte ďalej"
..........
Exactly the same error on localhost.

`Fatal error: Uncaught LogicException: An invariant has failed in C:\xampp\htdocs\Pulsecms51b2\pulsecore\dbc.php:12 Stack trace: #0 C:\xampp\htdocs\Pulsecms51b2\inc\tags\blog.php(40): pulsecore\invariant(false) #1 C:\xampp\htdocs\Pulsecms51b2\index.php(286): include('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\Pulsecms51b2\pulsecore\dbc.php on line 12`

**Comment by ghost** [comment]
Update pushed for the blog "more" link. That was the blog prefix from the configs being applied twice.
Ready for BETA3
